import fs from "fs";
import path from "path";
import * as p from "@clack/prompts";
import { writeConfig, getVoidhubDir } from "../lib/config";
import type { VoidHubConfig } from "../types";
import { detectGitHubUsername, pushVoidhub } from "../lib/git";

const DASHBOARD_TEMPLATE = `# 🌌 VoidHub Dashboard

> Central control for all apps. Auto-generated by \`voidhub sync\`.

| Name | Slug | Repo |
| ---- | ---- | ---- |
`;

export async function initCmd(): Promise<void> {
  const cwd = process.cwd();
  console.log(`\n🌌 Initializing VoidHub at: ${cwd}\n`);

  // 1. Base folder
  const baseInput = await p.text({
    message: "Base folder for your apps?",
    initialValue: cwd,
    validate: (v) => (v?.trim() ? undefined : "Base folder cannot be empty"),
  });
  if (p.isCancel(baseInput)) return p.cancel("Cancelled.");
  const base = baseInput as string;

  // 2. GitHub username
  const detected = detectGitHubUsername();
  let username: string;

  if (detected) {
    const useDetected = await p.confirm({
      message: `Detected GitHub username "${detected}". Use this?`,
      initialValue: true,
    });
    if (p.isCancel(useDetected)) return p.cancel("Cancelled.");

    if (useDetected) {
      username = detected;
    } else {
      const input = await p.text({ message: "Enter your GitHub username:" });
      if (p.isCancel(input)) return p.cancel("Cancelled.");
      username = input as string;
    }
  } else {
    const input = await p.text({ message: "Enter your GitHub username:" });
    if (p.isCancel(input)) return p.cancel("Cancelled.");
    username = input as string;
  }

  // 3. Write config
  const config: VoidHubConfig = { base, username };
  writeConfig(config);

  // 4. Create dashboard README if missing
  const voidhubDir = getVoidhubDir(base);
  const dashboardPath = path.join(voidhubDir, "README.md");
  if (!fs.existsSync(dashboardPath)) {
    fs.writeFileSync(dashboardPath, DASHBOARD_TEMPLATE);
  }

  // 5. Push to GitHub
  console.log("\n⬆️  Backing up .voidhub to GitHub...");
  pushVoidhub(config);

  // 6. Summary
  console.log(`
✅ VoidHub initialized!
   Base folder : ${base}
   Username    : ${username}
   Dashboard   : ${dashboardPath}
  `);
}