import fs from "fs";
import path from "path";
import { readConfig, getVoidhubDir } from "../lib/config";
import { discoverApps } from "../lib/apps";
import { pushVoidhub } from "../lib/git";
import type { DiscoveredApp } from "../types";

function buildDashboard(apps: DiscoveredApp[]): string {
  const rows = apps.map(({ manifest }) => {
    const repoLink = manifest.repo ? `[↗](${manifest.repo})` : "—";
    return `| ${manifest.name} | \`${manifest.slug}\` | ${repoLink} |`;
  });

  const table = [
    "| Name | Slug | Repo |",
    "| ---- | ---- | ---- |",
    ...rows,
  ].join("\n");

  return `# 🌌 VoidHub Dashboard

> Central control for all apps. Auto-generated by \`voidhub sync\`.

${table}
`;
}

export async function syncCmd(): Promise<void> {
  const config = readConfig();
  const voidhubDir = getVoidhubDir(config.base);
  const dashboardPath = path.join(voidhubDir, "README.md");

  // Scan the entire base directory recursively
  const apps = discoverApps(config.base);
  console.log(`\n🔍 Found ${apps.length} app(s).`);

  const content = buildDashboard(apps);
  fs.writeFileSync(dashboardPath, content);
  console.log(`📝 Dashboard updated: ${dashboardPath}`);

  console.log("\n⬆️  Pushing to GitHub...");
  pushVoidhub(config);
}